# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: tuesday-dev
  host: localhost
  user: ben

test:
  adapter: postgresql
  database: tuesday-test
  postgis_extension: true
  host: localhost
  user: ben


production:
  host:     localhost
  adapter:  postgresql
  database: tuesday-production
  username: ben
  password: test

